[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18.20.2"

[[redirects]]
  from = "/api/*"
  to = "https://www.analogstudios.net/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200