name: Main Integration

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing project dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Build
      run: |
        yarn clean && yarn build