name: Main Integration

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm ci
    - name: Build
      run: |
        npm run clean && npm run build
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        node deploy.js